# ./backend/nlp/dicts.py
# 自定义事件类型词典和地点名称词典
LABEL_TO_EVENT_TYPE = {
 'label_0': 'incentive',
 'label_1': 'greve', 
 'label_10': 'terremoto',        
 'label_100': 'igualdade',       
 'label_101': 'direitos humanos',
 'label_102': 'liberdade',       
 'label_103': 'justiça',
 'label_104': 'democracia',      
 'label_105': 'ditadura',
 'label_106': 'autocracia',
 'label_107': 'monarquia',
 'label_108': 'revolução',
 'label_109': 'golpe',
 'label_11': 'fome',
 'label_110': 'censura',
 'label_111': 'opressão',
 'label_112': 'exílio',
 'label_113': 'fuga',
 'label_114': 'refugiado',
 'label_115': 'migrante',
 'label_116': 'imigração',
 'label_117': 'emigração',
 'label_118': 'acolhimento',
 'label_119': 'abrigo',
 'label_12': 'inundação',
 'label_120': 'asileiro',
 'label_121': 'acampamento',
 'label_122': 'solidariedade',
 'label_123': 'ajuda humanitária',
 'label_124': 'fundos',
 'label_125': 'doação',
 'label_126': 'campanha de arrecadação',
 'label_127': 'voluntariado',
 'label_128': 'organização não governamental',
 'label_129': 'ONG',
 'label_13': 'temporal',
 'label_130': 'caridade',
 'label_131': 'auxílio',
 'label_132': 'subsídio',
 'label_133': 'subsidiado',
 'label_134': 'acordo bilateral',
 'label_135': 'ajuda externa',
 'label_136': 'governo estrangeiro',
 'label_137': 'intervenção',
 'label_138': 'cooperação',
 'label_139': 'divisão',
 'label_14': 'acidente',
 'label_140': 'unificação',
 'label_141': 'autossuficiência',
 'label_142': 'austeridade',
 'label_143': 'economia',
 'label_144': 'mercado',
 'label_145': 'negócios',
 'label_146': 'empresa',
 'label_147': 'indústria',
 'label_148': 'emprego',
 'label_149': 'desemprego',
 'label_15': 'atentado',
 'label_150': 'salário',
 'label_151': 'tributação',
 'label_152': 'impostos',
 'label_153': 'fisco',
 'label_154': 'crédito',
 'label_155': 'dívida',
 'label_156': 'inflação',
 'label_157': 'investimentos',
 'label_158': 'exportação',
 'label_159': 'importação',
 'label_16': 'assassinato',
 'label_160': 'comércio',
 'label_161': 'indústria',
 'label_162': 'produção',
 'label_163': 'consumo',
 'label_164': 'preço',
 'label_165': 'renda',
 'label_166': 'superávit',
 'label_167': 'déficit',
 'label_168': 'recessão',
 'label_169': 'crescimento',
 'label_17': 'homicídio',
 'label_170': 'expansão',
 'label_171': 'lucro',
 'label_172': 'falência',
 'label_173': 'bancarrota',
 'label_174': 'reforma fiscal',
 'label_175': 'taxa de juros',
 'label_176': 'câmbio',
 'label_177': 'banco central',
 'label_178': 'mercado de capitais',
 'label_179': 'ações',
 'label_18': 'suicídio',
 'label_180': 'valores',
 'label_181': 'fundos de investimento',
 'label_182': 'especulação',
 'label_183': 'bolsa de valores',
 'label_184': 'capital',
 'label_185': 'finanças',
 'label_186': 'transações',
 'label_187': 'gerenciamento de risco',
 'label_188': 'multinacional',
 'label_189': 'transporte',
 'label_19': 'sequestro',
 'label_190': 'mobilidade',
 'label_191': 'infraestrutura',
 'label_192': 'transporte público',
 'label_193': 'rodovia',
 'label_194': 'aeroporto',
 'label_195': 'estação de trem',
 'label_196': 'portos',
 'label_197': 'avião',
 'label_198': 'navio',
 'label_199': 'trem',
 'label_2': 'protesto',
 'label_20': 'crime',
 'label_200': 'ônibus',
 'label_201': 'carro',
 'label_202': 'bicicleta',
 'label_203': 'caminho de ferro',
 'label_204': 'caminhão',
 'label_205': 'trânsito',
 'label_206': 'congestionamento',
 'label_207': 'transporte coletivo',
 'label_208': 'custo de transporte',
 'label_209': 'logística',
 'label_21': 'violência',
 'label_210': 'rede ferroviária',
 'label_211': 'ferrovia',
 'label_212': 'crise de transporte',
 'label_213': 'greve de motoristas',
 'label_214': 'turismo',
 'label_215': 'viagem',
 'label_216': 'destino',
 'label_217': 'agência de viagens',
 'label_218': 'hotel',
 'label_219': 'passagem',
 'label_22': 'roubo',
 'label_220': 'aeroporto',
 'label_221': 'reserva',
 'label_222': 'guia turístico',
 'label_223': 'excursão',
 'label_224': 'atrações',
 'label_225': 'parques',
 'label_226': 'praia',
 'label_227': 'montanha',
 'label_228': 'cultura',
 'label_229': 'museu',
 'label_23': 'assalto',
 'label_230': 'exposição',
 'label_231': 'arte',
 'label_232': 'música',
 'label_233': 'cinema',
 'label_234': 'teatro',
 'label_235': 'livro',
 'label_236': 'literatura',
 'label_237': 'dança',
 'label_238': 'gastronomia',
 'label_239': 'culinária',
 'label_24': 'fraude',
 'label_240': 'gastrônomo',
 'label_241': 'restaurante',
 'label_242': 'chefe de cozinha',
 'label_243': 'culinária típica',
 'label_244': 'evento cultural',
 'label_245': 'festival',
 'label_246': 'festa',
 'label_247': 'tradicional',
 'label_248': 'religião',
 'label_249': 'fé',
 'label_25': 'corrupção',
 'label_250': 'igreja',
 'label_251': 'santuário',
 'label_252': 'celebração',
 'label_253': 'festividade',
 'label_254': 'ritual',
 'label_255': 'oração',
 'label_256': 'comemoração',
 'label_257': 'feriado',
 'label_258': 'aniversário',
 'label_259': 'festa religiosa',
 'label_26': 'polícia',
 'label_260': 'comunidade',
 'label_261': 'sociedade',
 'label_262': 'cidadão',
 'label_263': 'direitos civis',
 'label_264': 'luta social',
 'label_265': 'movimento',
 'label_266': 'engajamento',
 'label_267': 'advocacia',
 'label_268': 'consciência',
 'label_269': 'progresso',
 'label_27': 'investigação',
 'label_270': 'inovação',
 'label_271': 'tecnologia',
 'label_272': 'ciência',
 'label_273': 'pesquisa',
 'label_274': 'universidade',
 'label_275': 'educação',
 'label_276': 'ensino',
 'label_277': 'aprendizado',
 'label_278': 'currículo',
 'label_279': 'professor',
 'label_28': 'prisão',
 'label_280': 'aluno',
 'label_281': 'escola',
 'label_282': 'universitário',
 'label_283': 'ensino superior',
 'label_284': 'formação',
 'label_285': 'capacitação',
 'label_286': 'qualificação',
 'label_287': 'pesquisador',
 'label_288': 'publicação',
 'label_289': 'resultados',
 'label_29': 'tribunal',
 'label_290': 'conhecimento',
 'label_291': 'cultura acadêmica',
 'label_292': 'saúde',
 'label_293': 'medicina',
 'label_294': 'doença',
 'label_295': 'cura',
 'label_296': 'tratamento',
 'label_297': 'vacina',
 'label_298': 'epidemia',
 'label_299': 'pandemia',
 'label_3': 'manifestação',
 'label_30': 'processo',
 'label_300': 'hospital',
 'label_301': 'clínica',
 'label_302': 'médico',
 'label_303': 'enfermeiro',
 'label_304': 'profissional de saúde',
 'label_305': 'sistema de saúde',
 'label_306': 'unidade de saúde',
 'label_307': 'assistência',
 'label_308': 'tratamento médico',
 'label_309': 'cirurgia',
 'label_31': 'julgamento',
 'label_310': 'hospitalização',
 'label_311': 'diagnóstico',
 'label_312': 'cura',
 'label_313': 'prescrição',
 'label_314': 'sintoma',
 'label_315': 'enfermidade',
 'label_316': 'fármaco',
 'label_317': 'prescrição',
 'label_318': 'farmácia',
 'label_319': 'serviços médicos',
 'label_32': 'sentença',
 'label_320': 'assistência médica',
 'label_321': 'emergência',
 'label_322': 'leito hospitalar',
 'label_323': 'medicação',
 'label_324': 'plano de saúde',
 'label_325': 'sistema de saúde pública',
 'label_326': 'saúde mental',
 'label_327': 'psiquiatria',
 'label_328': 'psicologia',
 'label_329': 'abuso de substâncias',
 'label_33': 'detenção',
 'label_330': 'tratamento psicológico',
 'label_331': 'terapia',
 'label_332': 'psicoterapia',
 'label_333': 'saúde preventiva',
 'label_334': 'acompanhamento médico',
 'label_335': 'exame',
 'label_336': 'analises clínicas',
 'label_337': 'crítica',
 'label_338': 'opinião',
 'label_339': 'comentário',
 'label_34': 'libertação',
 'label_340': 'análise',
 'label_341': 'artigo',
 'label_342': 'jornal',
 'label_343': 'revista',
 'label_344': 'imprensa',
 'label_345': 'mídia',
 'label_346': 'notícia',
 'label_347': 'reportagem',
 'label_348': 'editorial',
 'label_349': 'entrevista',
 'label_35': 'prisão domiciliar',
 'label_350': 'fotografia',
 'label_351': 'vídeo',
 'label_352': 'documentário',
 'label_353': 'transmissão',
 'label_354': 'radialista',
 'label_355': 'jornalista',
 'label_356': 'editor',
 'label_357': 'publicação',
 'label_358': 'revisão',
 'label_359': 'meio de comunicação',
 'label_36': 'perseguição',
 'label_360': 'fakenews',
 'label_361': 'notícia falsa',
 'label_362': 'verificação',
 'label_363': 'informação',
 'label_364': 'desinformação',
 'label_365': 'evidência',
 'label_366': 'dados',
 'label_367': 'resultados',
 'label_368': 'estatísticas',
 'label_369': 'relatório',
 'label_37': 'extorsão',
 'label_370': 'pesquisa',
 'label_371': 'sondagem',
 'label_372': 'indicadores',
 'label_373': 'medição',
 'label_374': 'monitoramento',
 'label_375': 'comunicação',
 'label_376': 'disseminação',
 'label_377': 'campanha publicitária',
 'label_378': 'marketing',
 'label_379': 'publicidade',
 'label_38': 'abuso',
 'label_380': 'lançamento',
 'label_381': 'promoção',
 'label_382': 'publicidade',
 'label_383': 'conteúdo',
 'label_384': 'produtos',
 'label_385': 'mercado-alvo',
 'label_386': 'mídia digital',
 'label_387': 'influenciador',
 'label_388': 'rede social',
 'label_389': 'interação',
 'label_39': 'discriminação',
 'label_390': 'curtidas',
 'label_391': 'comentários',
 'label_392': 'compartilhamentos',
 'label_393': 'youtube',
 'label_394': 'facebook',
 'label_395': 'twitter',
 'label_396': 'instagram',
 'label_397': 'whatsapp',
 'label_398': 'aplicativo',
 'label_399': 'ferramenta digital',
 'label_4': 'rebelião',
 'label_40': 'racismo',
 'label_400': 'tecnologia da informação',
 'label_401': 'transformação digital',
 'label_402': 'indústria 4.0',
 'label_403': 'automação',
 'label_404': 'inteligência artificial',
 'label_405': 'big data',
 'label_406': 'cloud computing',
 'label_407': 'blockchain',
 'label_408': 'internet das coisas',
 'label_409': '5G',
 'label_41': 'xenofobia',
 'label_410': 'computação em nuvem',
 'label_411': 'software',
 'label_412': 'hardware',
 'label_413': 'computador',
 'label_414': 'cibersegurança',
 'label_415': 'privacidade',
 'label_416': 'proteção de dados',
 'label_417': 'redes sociais',
 'label_418': 'ciberbullying',
 'label_419': 'fake news',
 'label_42': 'homofobia',
 'label_420': 'mídia social',
 'label_421': 'influência digital',
 'label_422': 'rede de contatos',
 'label_423': 'marketing digital',
 'label_424': 'vendas online',
 'label_425': 'compras online',
 'label_426': 'e-commerce',
 'label_427': 'plataforma digital',
 'label_428': 'negócios digitais',
 'label_429': 'distribuição online',
 'label_43': 'genocídio',
 'label_430': 'vendas móveis',
 'label_431': 'transformação digital',
 'label_432': 'criptomoeda',
 'label_433': 'fintech',
 'label_434': 'startups',
 'label_435': 'economia digital',
 'label_436': 'internet',
 'label_437': 'tecnologia',
 'label_438': 'acesso à informação',
 'label_439': 'conectividade',
 'label_44': 'tortura',
 'label_440': 'conectado',
 'label_441': 'banda larga',
 'label_442': 'wi-fi',
 'label_443': 'internet móvel',
 'label_444': 'acesso à internet',
 'label_445': 'conectividade digital',
 'label_446': 'redes móveis',
 'label_447': '4G',
 'label_448': '5G',
 'label_449': 'cobertura',
 'label_45': 'tensão',
 'label_450': 'infraestrutura digital',
 'label_451': 'rede de fibra óptica',
 'label_452': 'impeachment presidencial',
 'label_453': 'instabilidade política',
 'label_454': 'crise constitucional',
 'label_455': 'reforma administrativa',
 'label_456': 'votação secretacomissão parlamentar',
 'label_457': 'diplomata',
 'label_458': 'embaixador',
 'label_459': 'tratado internacional',
 'label_46': 'embargo',
 'label_460': 'soberania nacionalconsulta popular',
 'label_461': 'congresso nacional',
 'label_462': 'autonomia regional',
 'label_463': 'pacto federativo',
 'label_464': 'intervenção militarcensura governamental',
 'label_465': 'ditador',
 'label_466': 'golpe parlamentar',
 'label_467': 'exílio político',
 'label_468': 'resistência civilpleito eleitoral',
 'label_469': 'política externa',
 'label_47': 'sanção',
 'label_470': 'proteção de fronteiras',
 'label_471': 'movimentos separatistas',
 'label_472': 'federalismo',
 'label_473': 'austeridade fiscal',
 'label_474': 'inflação galopante',
 'label_475': 'dívida pública',
 'label_476': 'mercado informal',
 'label_477': 'tributos federaisrenúncia fiscal',
 'label_478': 'carga tributária',
 'label_479': 'produtividade',
 'label_48': 'diplomacia',
 'label_480': 'outsourcing',
 'label_481': 'terceirizaçãodéficit fiscal',
 'label_482': 'crescimento exponencial',
 'label_483': 'pacto econômico',
 'label_484': 'subsídio agrícola',
 'label_485': 'isenção tributáriasalário mínimo',
 'label_486': 'salário bruto',
 'label_487': 'economia circular',
 'label_488': 'taxa cambial',
 'label_489': 'exportadorimportador',
 'label_49': 'acordo',
 'label_490': 'câmbio flutuante',
 'label_491': 'moeda estrangeira',
 'label_492': 'mercado imobiliário',
 'label_493': 'crise bancária',
 'label_494': 'discriminação de gênero',
 'label_495': 'violência contra a mulher',
 'label_496': 'direitos trabalhistas',
 'label_497': 'abuso de poder',
 'label_498': 'assédio sexualdesigualdade social',
 'label_499': 'exclusão social',
 'label_5': 'crise',
 'label_50': 'tratado',
 'label_500': 'preconceito',
 'label_501': 'casamento infantil',
 'label_502': 'exploração infantilviolência doméstica',
 'label_503': 'abandono parental',
 'label_504': 'tráfico humano',
 'label_505': 'abuso emocional',
 'label_506': 'proteção infantiljustiça restaurativa',
 'label_507': 'campanha humanitária',
 'label_508': 'crise habitacional',
 'label_509': 'direito à moradia',
 'label_51': 'negociação',
 'label_510': 'assistência socialações comunitárias',
 'label_511': 'reparação histórica',
 'label_512': 'luta por igualdade',
 'label_513': 'direitos das mulheres',
 'label_514': 'trabalho forçado',
 'label_515': 'epidemia local',
 'label_516': 'vacinação em massa',
 'label_517': 'centro de saúde',
 'label_518': 'tratamento preventivo',
 'label_519': 'pandemia globalhigiene sanitária',
 'label_52': 'conciliação',
 'label_520': 'surtos epidemiológicos',
 'label_521': 'controle de doenças',
 'label_522': 'uso de máscaras',
 'label_523': 'telemedicinapsicologia clínica',
 'label_524': 'saúde mental coletiva',
 'label_525': 'diagnóstico precoce',
 'label_526': 'tratamento alternativo',
 'label_527': 'medicina integrativaserviço de emergência',
 'label_528': 'medicação essencial',
 'label_529': 'controle de infecções',
 'label_53': 'mediação',
 'label_530': 'clínica geral',
 'label_531': 'hospital universitáriocuidado paliativo',
 'label_532': 'leito de UTI',
 'label_533': 'transplante de órgãos',
 'label_534': 'doação de sangue',
 'label_535': 'assistência domiciliar',
 'label_536': 'desmatamento ilegal',
 'label_537': 'poluição atmosférica',
 'label_538': 'aquecimento global',
 'label_539': 'mudança climática',
 'label_54': 'parceria',
 'label_540': 'energia renovávelcrise hídrica',
 'label_541': 'proteção florestal',
 'label_542': 'biodiversidade',
 'label_543': 'conservação ambiental',
 'label_544': 'impacto ambientaldesastre ecológico',
 'label_545': 'reciclagem',
 'label_546': 'gestão de resíduos',
 'label_547': 'preservação de rios',
 'label_548': 'política ambientalincêndios florestais',
 'label_549': 'tempestades severas',
 'label_55': 'aliança',
 'label_550': 'erosão costeira',
 'label_551': 'alagamento urbano',
 'label_552': 'desabamentomonitoramento climático',
 'label_553': 'energia solar',
 'label_554': 'energia eólica',
 'label_555': 'uso sustentável',
 'label_556': 'reflorestamento',
 'label_557': 'inovação tecnológica',
 'label_558': 'inteligência artificial',
 'label_559': 'cibersegurança',
 'label_56': 'cooperativa',
 'label_560': 'blockchain',
 'label_561': 'computação em nuvemtransformação digital',
 'label_562': 'automação industrial',
 'label_563': 'robótica avançada',
 'label_564': 'big data',
 'label_565': '5Gredes neurais',
 'label_566': 'realidade aumentada',
 'label_567': 'realidade virtual',
 'label_568': 'metaverso',
 'label_569': 'desenvolvimento de softwarecomputação quântica',
 'label_57': 'acordo comercial',
 'label_570': 'internet das coisas',
 'label_571': 'aprendizado de máquina',
 'label_572': 'tecnologia sustentável',
 'label_573': 'código abertoplataformas digitais',
 'label_574': 'aplicativos móveis',
 'label_575': 'redes sociais',
 'label_576': 'influenciadores digitais',
 'label_577': 'marketing online',
 'label_578': 'morte',
 'label_579': 'pandemia',
 'label_58': 'autonomia',
 'label_580': 'surto',
 'label_581': 'epicentro',
 'label_582': 'quarentena',
 'label_583': 'isolamento social',
 'label_584': 'lockdown',
 'label_585': 'emergência sanitária',
 'label_586': 'crise de saúde',
 'label_587': 'tratamento intensivo',
 'label_588': 'UTI lotada',
 'label_589': 'oxigênio',
 'label_59': 'independência',
 'label_590': 'intubação',
 'label_591': 'imunização',
 'label_592': 'vacinação',
 'label_593': 'doses de reforço',
 'label_594': 'cobertura vacinal',
 'label_595': 'mutação viral',
 'label_596': 'variante',
 'label_597': 'anticorpos',
 'label_598': 'ensaio clínico',
 'label_599': 'imunidade coletiva',
 'label_6': 'conflito',
 'label_60': 'separatismo',
 'label_600': 'taxa de contágio',
 'label_601': 'reabertura',
 'label_602': 'medidas de prevenção',
 'label_603': 'distanciamento físico',
 'label_604': 'protocolo sanitário',
 'label_605': 'restrição de viagens',
 'label_606': 'turismo afetado',
 'label_607': 'proibição de eventos',
 'label_608': 'uso de EPIs',
 'label_609': 'teletrabalho',
 'label_61': 'reconciliação',
 'label_610': 'ensino remoto',
 'label_611': 'aulas online',
 'label_612': 'férias coletivas',
 'label_613': 'recessos',
 'label_614': 'abertura parcial',
 'label_615': 'testagem em massa',
 'label_616': 'trabalho essencial',
 'label_617': 'escassez de insumos',
 'label_618': 'produção de vacinas',
 'label_619': 'centro de imunização',
 'label_62': 'paz',
 'label_620': 'fila de espera',
 'label_621': 'cobertura hospitalar',
 'label_622': 'plano de vacinação',
 'label_623': 'liberação emergencial',
 'label_624': 'relação médico-paciente',
 'label_625': 'ética médica',
 'label_626': 'orientação técnica',
 'label_627': 'mortalidade',
 'label_628': 'letalidade',
 'label_629': 'prognóstico',
 'label_63': 'cessar-fogo',
 'label_630': 'recuperação',
 'label_631': 'pós-operatório',
 'label_632': 'novos tratamentos',
 'label_633': 'avaliação clínica',
 'label_634': 'saúde pública',
 'label_635': 'infraestrutura hospitalar',
 'label_636': 'ambiente seguro',
 'label_637': 'capacidade máxima',
 'label_638': 'interrupção de serviços',
 'label_639': 'reposição de recursos',
 'label_64': 'desmilitarização',
 'label_640': 'fluxo migratório',
 'label_641': 'migração interna',
 'label_642': 'retorno ao lar',
 'label_643': 'gestão de fronteiras',
 'label_644': 'limite territorial',
 'label_645': 'restrição de circulação',
 'label_646': 'infraestrutura de acolhimento',
 'label_647': 'integração social',
 'label_648': 'orientação psicológica',
 'label_649': 'acolhimento de refugiados',
 'label_65': 'desarmamento',
 'label_650': 'trânsito internacional',
 'label_651': 'repatriação',
 'label_652': 'legalização migratória',
 'label_653': 'educação inclusiva',
 'label_654': 'curso técnico',
 'label_655': 'formação online',
 'label_656': 'capacitação remota',
 'label_657': 'adaptação escolar',
 'label_658': 'projetos pedagógicos',
 'label_659': 'ensino híbrido',
 'label_66': 'vitória',
 'label_660': 'educação especial',
 'label_661': 'alfabetização digital',
 'label_662': 'inclusão digital',
 'label_663': 'bolsa de estudos',
 'label_664': 'plataformas educativas',
 'label_665': 'acesso à educação',
 'label_666': 'inovação educacional',
 'label_667': 'avaliação contínua',
 'label_668': 'aprendizado remoto',
 'label_669': 'prática docente',
 'label_67': 'derrota',
 'label_670': 'adaptação curricular',
 'label_671': 'rede pública de ensino',
 'label_672': 'rede privada de ensino',
 'label_673': 'tutoria online',
 'label_674': 'suporte educacional',
 'label_675': 'programas de estágio',
 'label_676': 'atividade extracurricular',
 'label_677': 'dinâmicas virtuais',
 'label_678': 'competências socioemocionais',
 'label_679': 'acolhimento escolar',
 'label_68': 'eleições',
 'label_680': 'gestão pedagógica',
 'label_681': 'inclusão cultural',
 'label_682': 'parceria educacional',
 'label_683': 'trabalho voluntário',
 'label_684': 'empatia',
 'label_685': 'solidariedade',
 'label_686': 'engajamento coletivo',
 'label_687': 'projetos sociais',
 'label_688': 'conscientização comunitária',
 'label_689': 'ações emergenciais',
 'label_69': 'votação',
 'label_690': 'apoio psicossocial',
 'label_691': 'doações',
 'label_692': 'ajuda humanitária emergencial',
 'label_693': 'gestão de crise',
 'label_694': 'relato de experiência',
 'label_695': 'histórias de superação',
 'label_696': 'atendimento a vulneráveis',
 'label_697': 'programas de auxílio',
 'label_698': 'cestas básicas',
 'label_699': 'apoio financeiro',
 'label_7': 'guerra',
 'label_70': 'candidato',
 'label_700': 'atendimento remoto',
 'label_701': 'auxílio emergencial',
 'label_702': 'desafios logísticos',
 'label_703': 'transparência pública',
 'label_704': 'auditoria',
 'label_705': 'gestão responsável',
 'label_706': 'controle social',
 'label_707': 'parcerias estratégicas',
 'label_708': 'governança',
 'label_709': 'códigos de conduta',
 'label_71': 'presidente',
 'label_710': 'compliance',
 'label_711': 'políticas internas',
 'label_712': 'liderança ética',
 'label_713': 'gestão de mudanças',
 'label_714': 'impactos econômicos',
 'label_715': 'plano de recuperação',
 'label_716': 'recessão global',
 'label_717': 'mercado de trabalho',
 'label_718': 'retomada econômica',
 'label_719': 'pequenos negócios',
 'label_72': 'governo',
 'label_720': 'empreendedorismo',
 'label_721': 'créditos emergenciais',
 'label_722': 'auxílio para empresas',
 'label_723': 'planos de redução de impacto',
 'label_724': 'transformação empresarial',
 'label_725': 'estratégias digitais',
 'label_726': 'desafios financeiros',
 'label_727': 'responsabilidade corporativa',
 'label_728': 'estímulos fiscais',
 'label_729': 'taxas de desemprego',
 'label_73': 'ministro',
 'label_730': 'criação de empregos',
 'label_731': 'mercado de startups',
 'label_732': 'tecnologias inovadoras',
 'label_733': 'circuito de inovação',
 'label_734': 'conferências online',
 'label_735': 'eventos híbridos',
 'label_736': 'plataformas de transmissão',
 'label_737': 'desenvolvimento de softwares',
 'label_738': 'treinamento corporativo',
 'label_739': 'comunicação empresarial',
 'label_74': 'parlamento',
 'label_740': 'marketing estratégico',
 'label_741': 'expansão comercial',
 'label_742': 'parcerias de negócios',
 'label_743': 'comércio exterior',
 'label_744': 'novas regulamentações',
 'label_745': 'acordos internacionais',
 'label_746': 'alianças estratégicas',
 'label_747': 'crescimento sustentável',
 'label_748': 'economia circular',
 'label_749': 'revolução digital',
 'label_75': 'congresso',
 'label_750': 'ambiente de trabalho remoto',
 'label_751': 'reuniões virtuais',
 'label_752': 'protocolos empresariais',
 'label_753': 'negociações globais',
 'label_754': 'tecnologia emergente',
 'label_755': 'cibersegurança empresarial',
 'label_756': 'plano de contingência',
 'label_757': 'redes de suporte',
 'label_758': 'ajuda bilateral',
 'label_759': 'intercâmbio tecnológico',
 'label_76': 'senado',
 'label_760': 'projetos sustentáveis',
 'label_761': 'energia limpa',
 'label_762': 'mobilidade urbana',
 'label_763': 'sistemas inteligentes',
 'label_764': 'cidades conectadas',
 'label_765': 'políticas climáticas',
 'label_766': 'educação ambiental',
 'label_767': 'gestão de recursos naturais',
 'label_768': 'redução de emissões',
 'label_769': 'preservação de habitats',
 'label_77': 'deputado',
 'label_770': 'restauração ambiental',
 'label_771': 'agricultura sustentável',
 'label_772': 'impacto social',
 'label_773': 'inclusão econômica',
 'label_774': 'gestão colaborativa',
 'label_775': 'modelos de governança',
 'label_776': 'desenvolvimento inclusivo',
 'label_777': 'inovação social',
 'label_778': 'acessibilidade',
 'label_779': 'transformação cultural',
 'label_78': 'senador',
 'label_780': 'valorização da diversidade',
 'label_781': 'respeito às diferenças',
 'label_782': 'movimentos cívicos',
 'label_783': 'mobilização pacífica',
 'label_784': 'engajamento digital',
 'label_785': 'protestos virtuais',
 'label_786': 'campanhas sociais',
 'label_787': 'redes de apoio',
 'label_788': 'impacto positivo',
 'label_789': 'vozes comunitárias',
 'label_79': 'câmara',
 'label_790': 'luta por direitos',
 'label_791': 'protagonismo feminino',
 'label_792': 'ativismo jovem',
 'label_793': 'gestão participativa',
 'label_794': 'democracia digital',
 'label_795': 'acesso universal',
 'label_796': 'direito à informação',
 'label_797': 'proteção da privacidade',
 'label_798': 'ética na tecnologia',
 'label_799': 'inteligência artificial ética',
 'label_8': 'desastre',
 'label_80': 'decreto',
 'label_800': 'ferramentas educacionais',
 'label_801': 'redes globais',
 'label_802': 'acordos multilaterais',
 'label_803': 'estratégias de cooperação',
 'label_804': 'gestão intergovernamental',
 'label_805': 'projetos multilaterais',
 'label_806': 'negociações de paz',
 'label_807': 'soluções colaborativas',
 'label_808': 'gestão de conflitos',
 'label_809': 'mediação internacional',
 'label_81': 'projeto de lei',
 'label_810': 'alianças humanitárias',
 'label_811': 'conferências de paz',
 'label_812': 'proteção de civis',
 'label_813': 'acordo de cessar-fogo',
 'label_814': 'reconstrução pós-guerra',
 'label_815': 'justiça internacional',
 'label_816': 'resolução de disputas',
 'label_817': 'diálogo intercultural',
 'label_818': 'ações de reconciliação',
 'label_819': 'promessas de paz',
 'label_82': 'reforma',
 'label_820': 'alianças regionais',
 'label_821': 'cooperação transfronteiriça',
 'label_822': 'projetos de integração',
 'label_823': 'gestão de fronteiras',
 'label_824': 'mobilidade regional',
 'label_825': 'investimentos bilaterais',
 'label_826': 'infraestrutura compartilhada',
 'label_827': 'gestão de riscos',
 'label_828': 'redução de desigualdades',
 'label_829': 'justiça social',
 'label_83': 'protesto social',
 'label_830': 'acesso a oportunidades',
 'label_831': 'educação para todos',
 'label_832': 'tecnologias acessíveis',
 'label_833': 'saúde global',
 'label_834': 'bem-estar social',
 'label_835': 'empoderamento de comunidades',
 'label_836': 'fomento cultural',
 'label_837': 'valorização das tradições',
 'label_838': 'preservação do patrimônio',
 'label_839': 'turismo sustentável',
 'label_84': 'mobilização',
 'label_840': 'experiências autênticas',
 'label_841': 'economia criativa',
 'label_842': 'eventos interativos',
 'label_843': 'tecnologia imersiva',
 'label_844': 'realidade aumentada',
 'label_845': 'realidade virtual em eventos',
 'label_846': 'plataformas colaborativas',
 'label_847': 'soluções open-source',
 'label_848': 'redes descentralizadas',
 'label_849': 'impacto econômico positivo',
 'label_85': 'manifestante',
 'label_850': 'parcerias duradouras',
 'label_851': 'desenvolvimento local',
 'label_852': 'educação global',
 'label_853': 'conexões internacionais',
 'label_854': 'alianças multiculturais',
 'label_855': 'diálogo global',
 'label_856': 'impactos culturais',
 'label_857': 'divulgação de conhecimento',
 'label_858': 'rede de contatos profissionais',
 'label_859': 'mobilização em rede',
 'label_86': 'campanha',
 'label_860': 'empatia global',
 'label_861': 'protagonismo social',
 'label_862': 'ações transformadoras',
 'label_863': 'ideias inovadoras',
 'label_864': 'valorização dos saberes locais',
 'label_865': 'preservação da memória coletiva',
 'label_87': 'discurso',
 'label_88': 'debate',
 'label_89': 'denúncia',
 'label_9': 'incêndio',
 'label_90': 'acusações',
 'label_91': 'investigação',
 'label_92': 'suborno',
 'label_93': 'transparência',
 'label_94': 'impeachment',
 'label_95': 'responsabilidade',
 'label_96': 'referendo',
 'label_97': 'plebiscito',
 'label_98': 'política pública',
 'label_99': 'reconhecimento'}

EVENT_TYPE_KEYWORDS = {
"incentivo", "greve", "protesto", "manifestação", "rebelião", "crise", "conflito", "guerra", "desastre", "incêndio", 
"terremoto", "fome", "inundação", "temporal", "acidente", "atentado", "assassinato", "homicídio", "suicídio", 
"sequestro", "crime", "violência", "roubo", "assalto", "fraude", "corrupção", "polícia", "investigação", 
"prisão", "tribunal", "processo", "julgamento", "sentença", "detenção", "libertação", "prisão domiciliar", 
"perseguição", "extorsão", "abuso", "discriminação", "racismo", "xenofobia", "homofobia", "genocídio", "tortura", 
"tensão", "embargo", "sanção", "diplomacia", "acordo", "tratado", "negociação", "conciliação", "mediação", 
"parceria", "aliança", "cooperativa", "acordo comercial", "autonomia", "independência", "separatismo", "reconciliação", 
"paz", "cessar-fogo", "desmilitarização", "desarmamento", "vitória", "derrota", "eleições", "votação", "candidato", 
"presidente", "governo", "ministro", "parlamento", "congresso", "senado", "deputado", "senador", "câmara", "decreto", 
"projeto de lei", "reforma", "protesto social", "mobilização", "manifestante", "campanha", "discurso", "debate", 
"denúncia", "acusações", "investigação", "suborno", "transparência", "impeachment", "responsabilidade", "referendo", 
"plebiscito", "política pública", "reconhecimento", "igualdade", "direitos humanos", "liberdade", "justiça", 
"democracia", "ditadura", "autocracia", "monarquia", "revolução", "golpe", "censura", "opressão", "exílio", "fuga", 
"refugiado", "migrante", "imigração", "emigração", "acolhimento", "abrigo", "asileiro", "acampamento", "solidariedade", 
"ajuda humanitária", "fundos", "doação", "campanha de arrecadação", "voluntariado", "organização não governamental", 
"ONG", "caridade", "auxílio", "subsídio", "subsidiado", "acordo bilateral", "ajuda externa", "governo estrangeiro", 
"intervenção", "cooperação", "divisão", "unificação", "autossuficiência", "austeridade", "economia", "mercado", "negócios", 
"empresa", "indústria", "emprego", "desemprego", "salário", "tributação", "impostos", "fisco", "crédito", "dívida", 
"inflação", "investimentos", "exportação", "importação", "comércio", "indústria", "produção", "consumo", "preço", 
"renda", "superávit", "déficit", "recessão", "crescimento", "expansão", "lucro", "falência", "bancarrota", "reforma fiscal", 
"taxa de juros", "câmbio", "banco central", "mercado de capitais", "ações", "valores", "fundos de investimento", 
"especulação", "bolsa de valores", "capital", "finanças", "transações", "gerenciamento de risco", "multinacional", 
"transporte", "mobilidade", "infraestrutura", "transporte público", "rodovia", "aeroporto", "estação de trem", "portos", 
"avião", "navio", "trem", "ônibus", "carro", "bicicleta", "caminho de ferro", "caminhão", "trânsito", "congestionamento", 
"transporte coletivo", "custo de transporte", "logística", "rede ferroviária", "ferrovia", "crise de transporte", "greve de motoristas", 
"turismo", "viagem", "destino", "agência de viagens", "hotel", "passagem", "aeroporto", "reserva", "guia turístico", 
"excursão", "atrações", "parques", "praia", "montanha", "cultura", "museu", "exposição", "arte", "música", "cinema", 
"teatro", "livro", "literatura", "dança", "gastronomia", "culinária", "gastrônomo", "restaurante", "chefe de cozinha", 
"culinária típica", "evento cultural", "festival", "festa", "tradicional", "religião", "fé", "igreja", "santuário", 
"celebração", "festividade", "ritual", "oração", "comemoração", "feriado", "aniversário", "festa religiosa", 
"comunidade", "sociedade", "cidadão", "direitos civis", "luta social", "movimento", "engajamento", "advocacia", 
"consciência", "progresso", "inovação", "tecnologia", "ciência", "pesquisa", "universidade", "educação", "ensino", 
"aprendizado", "currículo", "professor", "aluno", "escola", "universitário", "ensino superior", "formação", 
"capacitação", "qualificação", "pesquisador", "publicação", "resultados", "conhecimento", "cultura acadêmica", 
"saúde", "medicina", "doença", "cura", "tratamento", "vacina", "epidemia", "pandemia", "hospital", "clínica", 
"médico", "enfermeiro", "profissional de saúde", "sistema de saúde", "unidade de saúde", "assistência", 
"tratamento médico", "cirurgia", "hospitalização", "diagnóstico", "cura", "prescrição", "sintoma", "enfermidade", 
"fármaco", "prescrição", "farmácia", "serviços médicos", "assistência médica", "emergência", "leito hospitalar", 
"medicação", "plano de saúde", "sistema de saúde pública", "saúde mental", "psiquiatria", "psicologia", "abuso de substâncias", 
"tratamento psicológico", "terapia", "psicoterapia", "saúde preventiva", "acompanhamento médico", "exame", "analises clínicas", 
"crítica", "opinião", "comentário", "análise", "artigo", "jornal", "revista", "imprensa", "mídia", "notícia", 
"reportagem", "editorial", "entrevista", "fotografia", "vídeo", "documentário", "transmissão", "radialista", "jornalista", 
"editor", "publicação", "revisão", "meio de comunicação", "fakenews", "notícia falsa", "verificação", "informação", 
"desinformação", "evidência", "dados", "resultados", "estatísticas", "relatório", "pesquisa", "sondagem", "indicadores", 
"medição", "monitoramento", "comunicação", "disseminação", "campanha publicitária", "marketing", "publicidade", 
"lançamento", "promoção", "publicidade", "conteúdo", "produtos", "mercado-alvo", "mídia digital", "influenciador", 
"rede social", "interação", "curtidas", "comentários", "compartilhamentos", "youtube", "facebook", "twitter", 
"instagram", "whatsapp", "aplicativo", "ferramenta digital", "tecnologia da informação", "transformação digital", 
"indústria 4.0", "automação", "inteligência artificial", "big data", "cloud computing", "blockchain", "internet das coisas", 
"5G", "computação em nuvem", "software", "hardware", "computador", "cibersegurança", "privacidade", "proteção de dados", 
"redes sociais", "ciberbullying", "fake news", "mídia social", "influência digital", "rede de contatos", "marketing digital", 
"vendas online", "compras online", "e-commerce", "plataforma digital", "negócios digitais", "distribuição online", 
"vendas móveis", "transformação digital", "criptomoeda", "fintech", "startups", "economia digital", "internet", 
"tecnologia", "acesso à informação", "conectividade", "conectado", "banda larga", "wi-fi", "internet móvel", 
"acesso à internet", "conectividade digital", "redes móveis", "4G", "5G", "cobertura", "infraestrutura digital", "rede de fibra óptica","impeachment presidencial", "instabilidade política", "crise constitucional", "reforma administrativa", "votação secreta"
"comissão parlamentar", "diplomata", "embaixador", "tratado internacional", "soberania nacional"
"consulta popular", "congresso nacional", "autonomia regional", "pacto federativo", "intervenção militar"
"censura governamental", "ditador", "golpe parlamentar", "exílio político", "resistência civil"
"pleito eleitoral", "política externa", "proteção de fronteiras", "movimentos separatistas", "federalismo","austeridade fiscal", "inflação galopante", "dívida pública", "mercado informal", "tributos federais"
"renúncia fiscal", "carga tributária", "produtividade", "outsourcing", "terceirização"
"déficit fiscal", "crescimento exponencial", "pacto econômico", "subsídio agrícola", "isenção tributária"
"salário mínimo", "salário bruto", "economia circular", "taxa cambial", "exportador"
"importador", "câmbio flutuante", "moeda estrangeira", "mercado imobiliário", "crise bancária","discriminação de gênero", "violência contra a mulher", "direitos trabalhistas", "abuso de poder", "assédio sexual"
"desigualdade social", "exclusão social", "preconceito", "casamento infantil", "exploração infantil"
"violência doméstica", "abandono parental", "tráfico humano", "abuso emocional", "proteção infantil"
"justiça restaurativa", "campanha humanitária", "crise habitacional", "direito à moradia", "assistência social"
"ações comunitárias", "reparação histórica", "luta por igualdade", "direitos das mulheres", "trabalho forçado","epidemia local", "vacinação em massa", "centro de saúde", "tratamento preventivo", "pandemia global"
"higiene sanitária", "surtos epidemiológicos", "controle de doenças", "uso de máscaras", "telemedicina"
"psicologia clínica", "saúde mental coletiva", "diagnóstico precoce", "tratamento alternativo", "medicina integrativa"
"serviço de emergência", "medicação essencial", "controle de infecções", "clínica geral", "hospital universitário"
"cuidado paliativo", "leito de UTI", "transplante de órgãos", "doação de sangue", "assistência domiciliar","desmatamento ilegal", "poluição atmosférica", "aquecimento global", "mudança climática", "energia renovável"
"crise hídrica", "proteção florestal", "biodiversidade", "conservação ambiental", "impacto ambiental"
"desastre ecológico", "reciclagem", "gestão de resíduos", "preservação de rios", "política ambiental"
"incêndios florestais", "tempestades severas", "erosão costeira", "alagamento urbano", "desabamento"
"monitoramento climático", "energia solar", "energia eólica", "uso sustentável", "reflorestamento","inovação tecnológica", "inteligência artificial", "cibersegurança", "blockchain", "computação em nuvem"
"transformação digital", "automação industrial", "robótica avançada", "big data", "5G"
"redes neurais", "realidade aumentada", "realidade virtual", "metaverso", "desenvolvimento de software"
"computação quântica", "internet das coisas", "aprendizado de máquina", "tecnologia sustentável", "código aberto"
"plataformas digitais", "aplicativos móveis", "redes sociais", "influenciadores digitais", "marketing online","morte",
"pandemia", "surto", "epicentro", "quarentena", "isolamento social", "lockdown", "emergência sanitária", "crise de saúde", 
"tratamento intensivo", "UTI lotada", "oxigênio", "intubação", "imunização", "vacinação", "doses de reforço", "cobertura vacinal",
"mutação viral", "variante", "anticorpos", "ensaio clínico", "imunidade coletiva", "taxa de contágio", "reabertura", "medidas de prevenção",
"distanciamento físico", "protocolo sanitário", "restrição de viagens", "turismo afetado", "proibição de eventos", "uso de EPIs", 
"teletrabalho", "ensino remoto", "aulas online", "férias coletivas", "recessos", "abertura parcial", "testagem em massa", "trabalho essencial",
"escassez de insumos", "produção de vacinas", "centro de imunização", "fila de espera", "cobertura hospitalar", "plano de vacinação", 
"liberação emergencial", "relação médico-paciente", "ética médica", "orientação técnica", "mortalidade", "letalidade", "prognóstico", 
"recuperação", "pós-operatório", "novos tratamentos", "avaliação clínica", "saúde pública", "infraestrutura hospitalar", "ambiente seguro", 
"capacidade máxima", "interrupção de serviços", "reposição de recursos", "fluxo migratório", "migração interna", "retorno ao lar", 
"gestão de fronteiras", "limite territorial", "restrição de circulação", "infraestrutura de acolhimento", "integração social", 
"orientação psicológica", "acolhimento de refugiados", "trânsito internacional", "repatriação", "legalização migratória", 
"educação inclusiva", "curso técnico", "formação online", "capacitação remota", "adaptação escolar", "projetos pedagógicos", 
"ensino híbrido", "educação especial", "alfabetização digital", "inclusão digital", "bolsa de estudos", "plataformas educativas", 
"acesso à educação", "inovação educacional", "avaliação contínua", "aprendizado remoto", "prática docente", "adaptação curricular", 
"rede pública de ensino", "rede privada de ensino", "tutoria online", "suporte educacional", "programas de estágio", "atividade extracurricular",
"dinâmicas virtuais", "competências socioemocionais", "acolhimento escolar", "gestão pedagógica", "inclusão cultural", 
"parceria educacional", "trabalho voluntário", "empatia", "solidariedade", "engajamento coletivo", "projetos sociais", 
"conscientização comunitária", "ações emergenciais", "apoio psicossocial", "doações", "ajuda humanitária emergencial", "gestão de crise",
"relato de experiência", "histórias de superação", "atendimento a vulneráveis", "programas de auxílio", "cestas básicas", "apoio financeiro",
"atendimento remoto", "auxílio emergencial", "desafios logísticos", "transparência pública", "auditoria", "gestão responsável", 
"controle social", "parcerias estratégicas", "governança", "códigos de conduta", "compliance", "políticas internas", 
"liderança ética", "gestão de mudanças", "impactos econômicos", "plano de recuperação", "recessão global", "mercado de trabalho", 
"retomada econômica", "pequenos negócios", "empreendedorismo", "créditos emergenciais", "auxílio para empresas", "planos de redução de impacto",
"transformação empresarial", "estratégias digitais", "desafios financeiros", "responsabilidade corporativa", "estímulos fiscais", 
"taxas de desemprego", "criação de empregos", "mercado de startups", "tecnologias inovadoras", "circuito de inovação", 
"conferências online", "eventos híbridos", "plataformas de transmissão", "desenvolvimento de softwares", "treinamento corporativo", 
"comunicação empresarial", "marketing estratégico", "expansão comercial", "parcerias de negócios", "comércio exterior", 
"novas regulamentações", "acordos internacionais", "alianças estratégicas", "crescimento sustentável", "economia circular",
"revolução digital", "ambiente de trabalho remoto", "reuniões virtuais", "protocolos empresariais", "negociações globais",
"tecnologia emergente", "cibersegurança empresarial", "plano de contingência", "redes de suporte", "ajuda bilateral", 
"intercâmbio tecnológico", "projetos sustentáveis", "energia limpa", "mobilidade urbana", "sistemas inteligentes", 
"cidades conectadas", "políticas climáticas", "educação ambiental", "gestão de recursos naturais", "redução de emissões", 
"preservação de habitats", "restauração ambiental", "agricultura sustentável", "impacto social", "inclusão econômica", 
"gestão colaborativa", "modelos de governança", "desenvolvimento inclusivo", "inovação social", "acessibilidade", 
"transformação cultural", "valorização da diversidade", "respeito às diferenças", "movimentos cívicos", "mobilização pacífica", 
"engajamento digital", "protestos virtuais", "campanhas sociais", "redes de apoio", "impacto positivo", "vozes comunitárias", 
"luta por direitos", "protagonismo feminino", "ativismo jovem", "gestão participativa", "democracia digital", 
"acesso universal", "direito à informação", "proteção da privacidade", "ética na tecnologia", "inteligência artificial ética", 
"ferramentas educacionais", "redes globais", "acordos multilaterais", "estratégias de cooperação", "gestão intergovernamental",
"projetos multilaterais", "negociações de paz", "soluções colaborativas", "gestão de conflitos", "mediação internacional", 
"alianças humanitárias", "conferências de paz", "proteção de civis", "acordo de cessar-fogo", "reconstrução pós-guerra", 
"justiça internacional", "resolução de disputas", "diálogo intercultural", "ações de reconciliação", "promessas de paz", 
"alianças regionais", "cooperação transfronteiriça", "projetos de integração", "gestão de fronteiras", "mobilidade regional", 
"investimentos bilaterais", "infraestrutura compartilhada", "gestão de riscos", "redução de desigualdades", "justiça social", 
"acesso a oportunidades", "educação para todos", "tecnologias acessíveis", "saúde global", "bem-estar social", 
"empoderamento de comunidades", "fomento cultural", "valorização das tradições", "preservação do patrimônio", 
"turismo sustentável", "experiências autênticas", "economia criativa", "eventos interativos", "tecnologia imersiva", 
"realidade aumentada", "realidade virtual em eventos", "plataformas colaborativas", "soluções open-source", 
"redes descentralizadas", "impacto econômico positivo", "parcerias duradouras", "desenvolvimento local", 
"educação global", "conexões internacionais", "alianças multiculturais", "diálogo global", "impactos culturais", 
"divulgação de conhecimento", "rede de contatos profissionais", "mobilização em rede", "empatia global", 
"protagonismo social", "ações transformadoras", "ideias inovadoras", "valorização dos saberes locais", "preservação da memória coletiva"

}


# 添加其他事件类型词典

# 定义葡萄牙地名词典 (例如葡萄牙主要城市)
PORTUGAL_LOCATIONS = {"Lisboa", "Porto", "Amadora", "Braga", "Coimbra", "Faro", "Évora", "Guarda", "Aveiro", "Leiria"
"Setúbal", "Viseu", "Viana do Castelo", "Funchal", "Ponta Delgada", "Cascais", "Sintra", "Matosinhos", "Maia", "Oeiras"
"Distrito de Lisboa", "Distrito do Porto", "Distrito de Setúbal", "Distrito de Faro", "Distrito de Coimbra", "Distrito de Évora", "Distrito de Aveiro"
"Distrito de Leiria", "Distrito de Braga", "Distrito de Viana do Castelo", "Distrito de Viseu", "Mosteiro dos Jerónimos", "Torre de Belém", "Palácio da Pena"
"Ponte Dom Luís I", "Castelo de São Jorge", "Oceanário de Lisboa", "Santuário de Fátima", "Universidade de Coimbra", "Museu Calouste Gulbenkian", "Serra da Estrela"
"Pico da Ilha do Pico", "Ilhas Berlengas", "Parque Nacional da Peneda-Gerês", "Quinta da Regaleira", "Baixa-Chiado", "Marquês de Pombal", "Campo Grande"
"Cais do Sodré", "Trindade", "São Bento", "Casa da Música", "Jardim Zoológico", "Saldanha", "Rato", "Oriente", "Alameda", "Colégio Militar"
"Santa Apolónia", "Senhora da Hora", "Estação Central", "Praça da Liberdade", "Av. dos Aliados", "Parque Eduardo VII", "Rossio", "Martim Moniz", "Gare do Oriente", "Avenida de Roma"
"Campo Pequeno", "Ribeira das Naus", "Praça de Espanha", "Avenida de Berna", "Universidade", "Campo das Cebolas", "Estação de Santa Apolónia", "Estação do Oriente", "Estação de São Bento"
"Estação de Campanhã", "Estação de Coimbra-B", "Estação de Sintra", "Estação de Aveiro", "Estação de Faro", "Estação de Braga", "Estação de Entrecampos", "Estação de Cascais"
"Estação de Setúbal", "Estação de Vila Real", "Estação de Beja", "Estação de Évora", "Igreja Anglicana", "Bragança", "Albufeira", "Alcácer do Sal", "Alcobaça", "Almada"
"Almeirim", "Alpiarça", "Angra do Heroísmo", "Arcos de Valdevez", "Barcelos", "Batalha", "Beja", "Bombarral", "Caldas da Rainha", "Cantanhede"
"Castelo Branco", "Chaves", "Covilhã", "Espinho", "Estarreja", "Felgueiras", "Gondomar", "Guimarães", "Horta", "Lagos"
"Lamego", "Loulé", "Mafra", "Mirandela", "Montemor-o-Novo", "Montijo", "Olhão", "Paredes", "Penafiel", "Peso da Régua"
"Portimão", "Póvoa de Varzim", "Santarém", "Seixal", "Sesimbra", "Tomar", "Torres Novas", "Torres Vedras", "Valença", "Valongo"
"Vila do Conde", "Vila Franca de Xira", "Vila Nova de Famalicão", "Vila Real de Santo António", "Vizela", "Estação de Valença", "Estação de Covilhã", "Estação de Guimarães"
"Estação de Portimão", "Estação de Viana do Castelo", "Estação de Odivelas", "Estação de Queluz", "Estação de Fátima", "Estação de Tomar", "Estação de Entroncamento"
"Estação de Caldas da Rainha", "Estação de Torres Vedras", "Estação de Vila Nova de Gaia", "Estação de Marco de Canaveses", "Estação de Espinho", "Estação de Ovar"
"Estação de Figueira da Foz", "Estação de Santa Cruz", "Estação de Tondela", "Estação de Loulé", "Estação de Lagos", "Estação de Silves", "Estação de Albufeira"
"Estação de Aveiro", "Estação de Alhandra", "Estação de Vialonga", "Estação de Entroncamento", "Estação de Vila Franca de Xira", "Estação de Areeiro", "Estação de Alvalade"
"Estação de Chelas", "Estação de Beato", "Estação de Moscavide", "Estação de Braço de Prata", "Estação de Algueirão", "Estação de Meleças", "Estação de Portalegre"
"Estação de Sines", "Estação de Santiago do Cacém", "Estação de Marvão", "Estação de Portas do Sol", "Estação de Vale de Santarém", "Estação de Tancos", "Estação de Barquinha"
"Estação de Almendra", "Estação de Freixo de Numão", "Estação de Pocinho", "Estação de Pinhão", "Estação de Régua", "Estação de Cete", "Estação de Recarei-Sobreira"
"Estação de Vizela", "Estação de Fafe", "Estação de Souselas", "Estação de Pampilhosa", "Estação de Cantanhede", "Estação de Oliveira do Bairro", "Estação de Oiã"
"Estação de Paredes", "Estação de Baltar", "Estação de Cête", "Estação de Paredes de Coura", "Estação de Vila Praia de Âncora", "Estação de Caminha", "Estação de Neiva"
"Estação de Darque", "Estação de Meadela", "Estação de Anadia", "Estação de Mealhada", "Estação de Lousã", "Estação de Serpins", "Estação de Vouzela"
"Praça do Comércio", "Praça do Município", "Praça da Figueira", "Praça do Marquês", "Praça do Rossio", "Avenida da Liberdade", "Avenida 5 de Outubro"
"Avenida Almirante Reis", "Rua Augusta", "Rua Garrett", "Rua do Ouro", "Rua de Santa Catarina", "Rua das Flores", "Rua Ferreira Borges", "Rua Sá da Bandeira"
"Avenida dos Descobrimentos", "Avenida Marginal", "Praça Luís de Camões", "Praça dos Restauradores", "Avenida Infante Dom Henrique", "Praça de D. Pedro IV", "Avenida do Atlântico"
"Avenida do Brasil", "Praça do Giraldo", "Rua do Carmo", "Parque Florestal de Monsanto", "Parque das Nações", "Parque do Monte Brasil", "Parque Biológico de Gaia"
"Parque Natural da Ria Formosa", "Parque Natural do Sudoeste Alentejano", "Parque Natural de Sintra-Cascais", "Reserva Natural do Estuário do Sado", "Parque da Cidade do Porto"
"Parque do Alvito", "Parque Eduardo VII", "Jardim Botânico de Coimbra", "Jardim Botânico do Porto", "Jardim do Torel", "Serra do Caramulo", "Serra de Monchique"
"Serra da Arrábida", "Serra de Aire e Candeeiros", "Serra do Marão", "Praia da Rocha", "Praia do Guincho", "Praia de Carcavelos", "Praia de Miramar", "Praia de Santa Cruz","Freguesia de Alcântara", "Freguesia de Benfica", "Freguesia de Lumiar", "Freguesia de Marvila", "Freguesia de Carnide"
"Freguesia de Arroios", "Freguesia de Ajuda", "Freguesia de São Vicente", "Freguesia de Santo António", "Freguesia de Penha de França"
"Freguesia de Alvalade", "Freguesia de Campo de Ourique", "Freguesia de Estrela", "Freguesia de Areeiro", "Freguesia de Belém"
"Freguesia de Santa Clara", "Freguesia de Olivais", "Freguesia de Campolide", "Freguesia de Beato", "Freguesia de Santa Maria Maior"
"Hospital de Santa Maria", "Hospital Curry Cabral", "Hospital Garcia de Orta", "Hospital São Francisco Xavier", "Hospital de Cascais"
"Hospital Lusíadas Lisboa", "Hospital dos Lusíadas Porto", "Hospital CUF Descobertas", "Hospital CUF Tejo", "Hospital CUF Porto"
"Instituto Português de Oncologia", "Hospital da Luz", "Hospital da Luz Oeiras", "Hospital da Luz Coimbra", "Hospital de Braga"
"Instituto Nacional de Saúde Doutor Ricardo Jorge", "Centro Hospitalar de Vila Nova de Gaia", "Hospital de Évora", "Hospital de Faro", "Hospital de Aveiro"
"Instituto Superior Técnico", "Universidade Nova de Lisboa", "Universidade de Lisboa", "Universidade Católica Portuguesa", "Universidade do Porto"
"Universidade do Minho", "Universidade de Coimbra", "Universidade dos Açores", "Universidade da Madeira", "Universidade de Aveiro"
"Instituto Politécnico de Lisboa", "Instituto Politécnico de Leiria", "Instituto Politécnico do Porto", "Escola Superior de Tecnologia de Setúbal", "Escola Superior de Enfermagem de Lisboa"
"Instituto Politécnico de Viana do Castelo", "Instituto Politécnico de Bragança", "Instituto Politécnico de Santarém", "Instituto Politécnico de Tomar", "Escola Superior de Educação de Coimbra"
"Escola Secundária de Camões", "Escola Secundária de Pedro Nunes", "Escola Secundária de Rainha Dona Amélia", "Escola Secundária de Afonso Domingues", "Escola Secundária de Dona Leonor"
"Escola Secundária de Passos Manuel", "Escola Secundária de Benfica", "Escola Secundária do Lumiar", "Escola Secundária de Odivelas", "Escola Secundária de Alvalade"
"Restaurante Ramiro", "Restaurante Solar dos Presuntos", "Restaurante Tavares Rico", "Restaurante A Cevicheria", "Restaurante Belcanto"
"Restaurante Alma", "Restaurante Marisqueira Ribamar", "Restaurante O Gaveto", "Restaurante Porto Santa Maria", "Restaurante Mar do Inferno"
"Restaurante Tasca do Chico", "Restaurante O Faia", "Restaurante Casa da Mariquinhas", "Restaurante Solar do Moinho", "Restaurante Adega do Alfredo"
"Restaurante Escondidinho", "Restaurante Abadia do Porto", "Restaurante Cantinho do Avillez", "Restaurante Zé dos Leitões", "Restaurante A Taberna da Rua das Flores"
"Centro Comercial Colombo", "Centro Comercial Vasco da Gama", "Centro Comercial Amoreiras", "Centro Comercial Alegro Alfragide", "Centro Comercial Dolce Vita Tejo"
"Centro Comercial Fórum Algarve", "Centro Comercial Fórum Coimbra", "Centro Comercial Fórum Madeira", "Centro Comercial Fórum Montijo", "Centro Comercial Fórum Barreiro"
"Centro Comercial NorteShopping", "Centro Comercial Braga Parque", "Centro Comercial Arrábida Shopping", "Centro Comercial Alameda Shop & Spot", "Centro Comercial MaiaShopping"
"Parque Jardim do Torel", "Parque Jardim do Príncipe Real", "Parque Jardim da Estrela", "Parque Jardim do Campo Grande", "Parque Jardim do Cerco de Mafra"
"Parque Jardim do Passeio Alegre", "Parque Jardim Botânico da Ajuda", "Parque Jardim Botânico do Porto", "Parque Jardim do Monte Agudo", "Parque Jardim da Alameda"
"Parque Jardim do Arco do Cego", "Parque Jardim de São Pedro de Alcântara", "Parque Jardim das Amoreiras", "Parque Jardim Fernando Pessoa", "Parque Jardim de Belém"
"Praia da Adraga", "Praia do Baleal", "Praia de São Julião", "Praia de Ribeira d'Ilhas", "Praia do Guincho"
"Praia da Figueira", "Praia da Zambujeira do Mar", "Praia do Meco", "Praia da Comporta", "Praia da Galé"
"Praia do Carvoeiro", "Praia de Dona Ana", "Praia da Rocha Baixinha", "Praia de Monte Gordo", "Praia do Barril"
"Praia do Burgau", "Praia da Marinha", "Praia de Benagil", "Praia do Amado", "Praia da Cordoama"
"Praia do Beliche", "Praia da Salema", "Praia da Luz", "Praia da Ilha Deserta", "Praia de Porto Santo"
"Agência Portuguesa do Ambiente", "Câmara Municipal de Lisboa", "Câmara Municipal do Porto", "Câmara Municipal de Braga", "Câmara Municipal de Coimbra"
"Câmara Municipal de Faro", "Câmara Municipal de Cascais", "Câmara Municipal de Sintra", "Câmara Municipal de Almada", "Câmara Municipal de Aveiro"
"Câmara Municipal de Setúbal", "Câmara Municipal de Évora", "Câmara Municipal de Guarda", "Câmara Municipal de Vila Real", "Câmara Municipal de Portimão"
"Câmara Municipal de Matosinhos", "Câmara Municipal de Maia", "Câmara Municipal de Oeiras", "Câmara Municipal de Leiria", "Câmara Municipal de Viana do Castelo"
"Parque Infantil dos Jardins da Torre", "Parque Infantil do Parque das Nações", "Parque Infantil do Jardim da Estrela", "Parque Infantil do Jardim do Torel", "Parque Infantil do Campo Grande"
"Parque Infantil do Jardim Botânico", "Parque Infantil do Jardim das Amoreiras", "Parque Infantil do Jardim de São Pedro de Alcântara", "Parque Infantil do Jardim de Belém", "Parque Infantil do Jardim da Alameda","Freguesia de São Domingos de Rana", "Freguesia de Carcavelos e Parede", "Freguesia de Almada", "Freguesia de Cacilhas", "Freguesia de Caparica e Trafaria"
"Freguesia de Charneca de Caparica e Sobreda", "Freguesia de Laranjeiro e Feijó", "Freguesia de Amora", "Freguesia de Corroios", "Freguesia de Fernão Ferro"
"Freguesia de Seixal, Arrentela e Aldeia de Paio Pires", "Freguesia de Quinta do Conde", "Freguesia de Sesimbra (Castelo)", "Freguesia de Sesimbra (Santiago)", "Freguesia de Quinta do Anjo"
"Freguesia de Palmela", "Freguesia de Pinhal Novo", "Freguesia de Alhos Vedros", "Freguesia de Baixa da Banheira e Vale da Amoreira", "Freguesia de Moita"
"Freguesia de Gaio-Rosário e Sarilhos Pequenos", "Freguesia de Barreiro e Lavradio", "Freguesia de Santo André", "Freguesia de Alto do Seixalinho", "Freguesia de Santo António da Charneca","Praia de Cacela Velha", "Praia da Ilha da Culatra", "Praia do Vale do Lobo", "Praia de Armação de Pêra", "Praia do Martinhal"
"Praia do Monte Clérigo", "Praia do Vale dos Homens", "Praia de Odeceixe", "Praia de Almograve", "Praia de Vila Nova de Milfontes"
"Praia da Zambujeira do Mar", "Praia do Tonel", "Praia de Sagres", "Praia da Adraga", "Praia de Cabanas"
"Praia de Altura", "Praia do Barranco", "Praia de Ferragudo", "Praia de Aljezur", "Praia de São Torpes"
"Praia da Franquia", "Praia do Amado", "Praia do Beliche", "Praia da Arrifana", "Praia do Zavial","Hospital de Portalegre", "Hospital Distrital de Santarém", "Centro de Saúde de Odivelas", "Centro de Saúde de Cascais", "Centro Hospitalar de Setúbal"
"Hospital de Vila Franca de Xira", "Hospital da Figueira da Foz", "Hospital de Torres Vedras", "Hospital de Castelo Branco", "Centro Hospitalar do Baixo Vouga"
"Unidade Local de Saúde do Alto Minho", "Hospital de Santo Tirso", "Hospital de Famalicão", "Hospital de Viana do Castelo", "Centro de Saúde de Ponte de Lima"
"Hospital de Monção", "Centro de Saúde de Chaves", "Centro de Saúde de Mirandela", "Hospital de Vila Real", "Hospital de Lamego"
"Hospital de Peso da Régua", "Hospital Distrital de Bragança", "Centro Hospitalar de Trás-os-Montes e Alto Douro", "Centro de Saúde de Valença", "Centro de Saúde de Melgaço","Restaurante A Brasileira", "Café Majestic", "Restaurante Cervejaria Trindade", "Restaurante Gambrinus", "Café Nicola"
"Restaurante Eleven", "Restaurante Feitoria", "Restaurante Pedro Lemos", "Restaurante Vila Joya", "Restaurante Ocean"
"Restaurante G Pousada", "Restaurante Loco", "Restaurante Esquina Carlos Teixeira", "Restaurante 100 Maneiras", "Restaurante Taberna do Mercado"
"Restaurante O Frade", "Restaurante O Velho Eurico", "Restaurante Solar dos Nunes", "Restaurante Tia Alice", "Restaurante Tasquinha do Oliveira"
"Café A Lanchonete", "Café Pão de Ló de Margaride", "Café Delta Q", "Café Afonso", "Café Grão da Vila","Parque Florestal de Monsanto", "Parque Urbano do Jamor", "Parque da Cidade do Porto", "Parque Verde do Mondego", "Parque Urbano de Odivelas"
"Parque da Quinta das Conchas e dos Lilases", "Parque Urbano de Miraflores", "Parque Urbano de Santa Iria da Azóia", "Parque das Nações", "Parque de Lazer de Albarraque"
"Parque de Lazer de Vale de Lobos", "Parque Ambiental do Buçaquinho", "Parque Natural de Montesinho", "Parque Natural do Douro Internacional", "Parque Natural da Serra da Malcata"
"Parque Natural da Arrábida", "Parque Natural do Tejo Internacional", "Parque Natural do Vale do Guadiana", "Reserva Natural do Estuário do Tejo", "Reserva Natural das Dunas de São Jacinto"
"Reserva Natural da Lagoa de Santo André", "Parque Botânico do Faial", "Parque do Luso", "Jardim da Cerca da Graça", "Jardim Botânico da Madeira""Fundação Calouste Gulbenkian", "Fundação Champalimaud", "Casa da Música", "Museu Nacional de Arte Antiga", "Museu do Fado"
"Museu dos Coches", "Museu da Marioneta", "Museu Nacional de Arqueologia", "Museu Nacional do Azulejo", "Centro Cultural de Belém"
"Casa Fernando Pessoa", "Teatro Nacional Dona Maria II", "Teatro Nacional São João", "Teatro Camões", "Teatro Aberto"
"Palácio Nacional de Mafra", "Palácio Nacional de Queluz", "Palácio Nacional da Ajuda", "Palácio Nacional de Sintra", "Castelo de Óbidos"
"Castelo de Montemor-o-Velho", "Castelo de Palmela", "Castelo de Alcoutim", "Castelo de Alvito", "Castelo de Marvão","Freguesia de Santo André (Barreiro)", "Freguesia de São Julião do Tojal", "Freguesia de Azeitão (Setúbal)", "Freguesia de Alhandra", "Freguesia de Azambuja"
"Freguesia de São Vicente de Fora", "Freguesia de Telheiras", "Freguesia de Quinta do Anjo (Palmela)", "Freguesia de Arcozelo (Barcelos)", "Freguesia de São Pedro da Afurada"
"Freguesia de Lavradio", "Freguesia de Paços de Ferreira", "Freguesia de Esmoriz", "Freguesia de Olival Basto", "Freguesia de Loures e Moscavide"
"Freguesia de Seia", "Freguesia de São João da Madeira", "Freguesia de Sever do Vouga", "Freguesia de Vila Nova de Paiva", "Freguesia de Penalva do Castelo"
"Freguesia de Vila Nova de Cerveira", "Freguesia de Valença do Minho", "Freguesia de Castro Laboreiro", "Freguesia de Paradela", "Freguesia de Brufe","Rua dos Bacalhoeiros", "Rua Nova do Almada", "Rua da Madalena", "Rua do Poço dos Negros", "Rua das Janelas Verdes"
"Rua de São Bento", "Rua de Cedofeita", "Rua do Almada (Porto)", "Rua do Infante Dom Henrique", "Rua Mouzinho da Silveira"
"Rua de Santa Maria (Óbidos)", "Praça do Município (Porto)", "Praça 8 de Maio (Coimbra)", "Praça de Santiago", "Praça Velha (Angra do Heroísmo)"
"Praça da República (Beja)", "Praça do Almada (Póvoa de Varzim)", "Rua Augusta (Lisboa)", "Rua do Carmo (Lisboa)", "Praça Luís de Camões (Lisboa)"
"Rua de São João (Guimarães)", "Praça da República (Évora)", "Praça da Alegria (Lisboa)", "Rua Miguel Bombarda (Porto)", "Rua Ferreira Borges (Porto)","Praia do Tonel (Sagres)", "Praia da Manta Rota", "Praia de Vale do Garrão", "Praia de Cabanas Velhas", "Praia do Homem do Leme"
"Praia de São Pedro de Moel", "Praia do Salgado (Nazaré)", "Praia da Lagoa de Albufeira", "Praia de Santo Amaro de Oeiras", "Praia da Parede"
"Praia do Tamariz", "Praia das Avencas", "Praia de São Torpes (Sines)", "Praia do Guincho (Cascais)", "Praia de Albufeira do Azibo"
"Praia da Ponta da Piedade (Lagos)", "Praia de Vale de Centeanes", "Praia da Amoreira", "Praia de Santa Eulália", "Praia da Cova do Vapor"
"Praia de Vale Furado", "Praia do Rei", "Praia das Conchas (Vila do Conde)", "Praia da Cornélia", "Praia do Coral""Hospital Distrital de Faro", "Centro Hospitalar Lisboa Ocidental", "Hospital de Santa Cruz (Carnaxide)", "Hospital de S. Bernardo (Setúbal)", "Hospital Dr. Francisco Zagalo (Ovar)"
"Hospital de Santo António (Porto)", "Hospital de Nossa Senhora da Oliveira (Guimarães)", "Hospital de São Teotónio (Viseu)", "Hospital São João Baptista (Entroncamento)", "Centro de Saúde de Mafra"
"Centro de Saúde de Póvoa de Santa Iria", "Centro de Saúde de Sacavém", "Centro de Saúde de Vila do Conde", "Centro de Saúde de Alenquer", "Centro de Saúde de Vila Nova de Gaia"
"Centro de Saúde da Quinta do Conde", "Hospital do Barreiro", "Hospital do Montijo", "Hospital de Pombal", "Hospital de Vendas Novas"
"Hospital de Oliveira do Bairro", "Hospital da Trofa", "Hospital de Barcelos", "Centro de Saúde de Ourém", "Centro de Saúde de Tomar","Centro Comercial Espaço Guimarães", "Centro Comercial Aqua Portimão", "Centro Comercial Gran-Plaza Tavira", "Centro Comercial Palácio do Gelo (Viseu)", "Centro Comercial El Corte Inglés (Lisboa)"
"Centro Comercial La Vie (Funchal)", "Centro Comercial Minho Center (Braga)", "Centro Comercial Dolce Vita Douro (Vila Real)", "Centro Comercial Madeira Shopping", "Centro Comercial Braga Parque"
"Sede da EDP (Lisboa)", "Sede da Galp Energia (Lisboa)", "Sede da Sonae (Maia)", "Sede do Banco Santander Totta (Lisboa)", "Sede da Jerónimo Martins (Lisboa)"
"Campus da Novabase (Lisboa)", "Centro Empresarial Lagoas Park", "Centro Empresarial Tagus Park", "Centro Empresarial Quinta da Fonte", "Edifício Almada Forum (Almada)"
"Centro Comercial Alegro Sintra", "Centro Comercial Alegro Montijo", "Centro Comercial Forum Sintra", "Centro Comercial Dolce Vita Porto", "Centro Comercial Forum Almada",
"Escola Secundária de D. Dinis (Lisboa)", "Escola Secundária António Damásio", "Escola Secundária Padre António Vieira", "Escola Secundária de São João do Estoril", "Escola Básica Integrada da Lourinhã"
"Escola Secundária de Caldas da Rainha", "Escola Secundária Infanta D. Maria (Coimbra)", "Escola Secundária Carolina Michaelis (Porto)", "Escola Secundária Jaime Moniz (Funchal)", "Escola Secundária de Ponta Delgada"
"Instituto Politécnico de Beja", "Instituto Politécnico de Portalegre", "Universidade Europeia (Lisboa)", "Universidade Fernando Pessoa (Porto)", "Universidade Lusófona do Porto"
"Universidade Lusíada de Lisboa", "Universidade Atlântica (Oeiras)", "Instituto Superior de Contabilidade e Administração do Porto", "Escola Superior de Saúde de Santarém", "Escola Superior Agrária de Elvas"
"Escola de Hotelaria e Turismo de Setúbal", "Escola de Hotelaria e Turismo do Estoril", "Instituto Politécnico da Guarda", "Escola Superior de Educação de Viseu", "Escola Secundária de Loulé","Reserva Natural do Paul de Arzila", "Reserva Natural do Paul do Boquilobo", "Parque Nacional da Peneda-Gerês", "Parque Natural das Serras de Aire e Candeeiros", "Serra do Açor"
"Cabo da Roca", "Cabo Espichel", "Cabo de São Vicente", "Ilha de Porto Santo", "Ilha do Corvo"
"Castelo de Linhares da Beira", "Castelo de Mértola", "Castelo de Aljezur", "Castelo de Arraiolos", "Castelo de Marialva"
"Museu de Alberto Sampaio (Guimarães)", "Museu da Eletricidade (Lisboa)", "Museu do Oriente (Lisboa)", "Museu da Água (Lisboa)", "Museu do Mar Rei D. Carlos (Cascais)"
"Casa de Camilo (Vila Nova de Famalicão)", "Mosteiro de Santa Clara-a-Velha (Coimbra)", "Mosteiro de Santa Maria de Alcobaça", "Mosteiro de Santa Maria da Vitória (Batalha)", "Mosteiro de São João de Tarouca",
"Parque Linear Ribeirinho do Estuário do Tejo", "Museu da Música Portuguesa", "Convento do Carmo", "Igreja de São Roque", "Mercado da Ribeira",
"Praia dos Três Irmãos", "Serra de Santa Luzia", "Catedral de Braga", "Centro de Interpretação da Serra da Estrela", "Aldeia Histórica de Monsanto",
"Cabo da Roca", "Praia da Falésia", "Parque Temático Zoomarine", "Ponta da Piedade", "Ilha do Farol", "Aldeia do Lindoso", "Castelo de Belmonte",
"Barragem do Alqueva", "Museu do Pão", "Vila Medieval de Óbidos", "Ponte de Lima", "Pico do Areeiro", "Miradouro da Senhora do Monte",
"Igreja de São Francisco (Porto)", "Jardim do Palácio de Cristal", "Castelo de Sabugal", "Reserva Natural das Berlengas", "Igreja do Carmo (Faro)",
"Forte de São Julião da Barra", "Convento de Cristo (Tomar)", "Vila de Marvão", "Palácio de Mateus", "Praia Formosa (Madeira)",
"Casa Museu Amália Rodrigues", "Lagoa das Sete Cidades", "Museu Militar de Lisboa", "Termas de Monfortinho", "Aldeia de Piódão",
"Castelo de Silves", "Igreja da Misericórdia (Aveiro)", "Capela dos Ossos (Évora)", "Parque Florestal das Fontes (Estômbar)", "Miradouro da Boca do Inferno",
"Forte de São João Baptista (Berlengas)", "Museu do Carro Elétrico (Porto)", "Sítio da Nazaré", "Lagoa das Furnas (Açores)", "Castelo de Almourol",
"Forte de São Vicente (Torres Vedras)", "Palácio de Monserrate", "Castelo de Linhares", "Ermida da Memória (Santuário da Nazaré)", "Igreja Matriz de Oeiras",
"Mercado do Bolhão (Porto)", "Parque Biológico de Gaia", "Aldeia da Pena (São Pedro do Sul)", "Igreja de Santo António (Lisboa)", "Igreja de Nossa Senhora do Castelo (Sesimbra)",
"Miradouro do Arco da Rua Augusta", "Barragem de Castelo do Bode", "Mosteiro de São Vicente de Fora", "Palácio da Brejoeira", "Cabo Girão (Madeira)",
"Igreja de Santa Maria de Marvila", "Parque Municipal do Monte da Virgem", "Museu de Lamego", "Capela de São Miguel (Coimbra)", "Palácio de São Bento (Lisboa)",
"Reserva Natural da Lagoa do Fogo", "Museu do Vinho do Porto", "Parque Florestal do Cabouco (Açores)", "Museu da Ciência da Universidade de Coimbra", "Praia do Vale Covo (Lagoa)",
"Castelo de Santa Maria da Feira", "Fortaleza de Sagres", "Igreja de São Pedro (Funchal)", "Centro de Ciência Viva de Tavira", "Parque Natural da Serra de São Mamede",
"Castelo de Aljezur", "Igreja Matriz de Caminha", "Igreja da Santíssima Trindade (Fátima)", "Parque Natural das Lagoas de Bertiandos e S. Pedro de Arcos", "Praia de Santa Bárbara (Açores)",
"Praia dos Salgados", "Termas de São Pedro do Sul", "Aldeia do Talasnal (Lousã)", "Museu da Quinta das Cruzes (Madeira)", "Jardim Tropical Monte Palace (Madeira)",
"Capela de Nossa Senhora da Boa Estrela (Serra da Estrela)", "Santuário da Penha (Guimarães)", "Aldeia de Sortelha", "Cais de Gaia", "Parque Ribeirinho de Vila Real de Santo António",
"Forte de São João da Barra (Cabanas)", "Museu do Traje (Viana do Castelo)", "Forte de São Miguel Arcanjo (Nazaré)", "Igreja de São Domingos (Lisboa)", "Palácio Nacional de Mafra",
"Praia de Moledo", "Museu Nacional do Teatro e da Dança (Lisboa)", "Praia do Tonel (Sagres)", "Museu do Design e da Moda (Lisboa)", "Igreja de Santo António (Porto)",
"Praia da Rainha (Cascais)", "Casa do Infante (Porto)", "Museu do Arroz (Comporta)", "Igreja de Santa Maria da Feira", "Castelo de Mértola",
"Praia do Beliche", "Igreja de Santa Clara-a-Nova (Coimbra)", "Museu Marítimo de Ílhavo", "Praia da Consolação", "Museu do Vidro (Marinha Grande)",
"Capela do Senhor da Pedra (Miramar)", "Castelo de Portel", "Museu do Fado (Lisboa)", "Museu de Portimão", "Museu dos Biscainhos (Braga)",
"Praia da Baía (Espinho)", "Reserva Natural do Sapal de Castro Marim e Vila Real de Santo António", "Miradouro das Portas do Sol (Santarém)", "Praia do Porto Santo", "Praia do Ribeiro do Cavalo (Sesimbra)",
"Centro de Interpretação do Vulcão dos Capelinhos", "Museu da Baleia da Madeira", "Museu do Traje de Viana do Castelo", "Praia do Paraíso (Carvoeiro)", "Praia do Barril (Tavira)",
"Capela da Nossa Senhora da Conceição (Tomar)", "Parque Urbano do Seixal", "Aldeia Histórica de Marialva", "Praia das Furnas (Odemira)", "Museu dos Descobrimentos (Belmonte)",
"Praia do Amado (Carrapateira)", "Igreja de São Gonçalo (Amarante)", "Museu de Arte Sacra (Funchal)", "Miradouro da Senhora do Salto", "Museu da Imagem (Braga)",
"Castelo de Penedono", "Praia de Carvoeiro", "Miradouro da Graça (Lisboa)", "Museu de Arte Contemporânea de Elvas", "Praia do Guincho (Cascais)",
"Jardim Botânico do Faial (Açores)", "Igreja de Santo António dos Capuchos (Guarda)", "Museu Arqueológico de São Miguel de Odrinhas", "Museu da Chapelaria (São João da Madeira)", "Museu da Terra de Miranda (Miranda do Douro)",
"Parque de Merendas do Pisão (Alvito)", "Parque das Merendas da Tapada Nacional de Mafra", "Igreja de São Bartolomeu (Borba)", "Casa do Brincar (Lisboa)", "Parque de Merendas de Melgaço",
"Praia da Adraga", "Praia da Arrifana", "Praia de Odeceixe", "Igreja Matriz de Póvoa de Varzim", "Praia de Aljezur",
"Parque Natural da Serra da Lousã", "Cascata do Tahiti (Peneda-Gerês)", "Mosteiro de Santa Clara-a-Velha", "Museu de Alberto Sampaio (Guimarães)", "Casa Museu Bissaya Barreto (Coimbra)",
"Estação de São Mamede", "Museu de Cera de Fátima", "Praia da Torreira", "Miradouro das Lagoas", "Caminho das Azenhas (Sintra)",
"Igreja de Nossa Senhora do Socorro (Portalegre)", "Biblioteca Municipal de Cascais", "Jardim da Quinta da Fonte", "Museu do Lagar (Castelo Branco)", "Praia do Camilo (Lagos)",
"Ermida de São Sebastião (Vila do Conde)", "Cine-Teatro João Verde (Monção)", "Teatro Tivoli BBVA (Lisboa)", "Centro Cultural de Carnide", "Parque de Merendas da Lagoa Azul",
"Igreja de São Martinho (Sever do Vouga)", "Palácio do Raio (Braga)", "Praia das Avencas (Parede)", "Centro de Interpretação do Megalitismo de Mora", "Casa da Cultura de Ponte da Barca",
"Capela de Nossa Senhora das Dores (Freixo de Espada à Cinta)", "Praia da Bafureira (Carcavelos)", "Estação de Carreiras", "Praia de São Martinho do Porto", "Museu das Rendas de Bilros (Vila do Conde)",
"Casa da Memória (Guimarães)", "Parque Urbano de Almeirim", "Praia Fluvial do Agroal", "Museu de Arte Pré-Histórica (Mação)", "Forte da Ínsua (Caminha)",
"Parque de Merendas do Rio Homem", "Reserva Florestal de Recreio do Monte da Guia (Faial)", "Praia do Seixo (Almagreira)", "Igreja de São Tiago (Torres Vedras)", "Parque de Lazer do Choupal (Alcácer do Sal)",
"Mercado do Levante (Loulé)", "Centro de Ciência Viva de Estremoz", "Forte da Graça (Elvas)", "Lagoa Comprida (Serra da Estrela)", "Miradouro da Senhora da Piedade (Lousã)",
"Praia Fluvial de Loriga", "Museu da Música Mecânica (Palmela)", "Praia do Barranco das Belharucas (Albufeira)", "Estação de Arentim", "Praia Fluvial de Unhais da Serra",
"Praia do Homem Nú (Alentejo)", "Biblioteca Municipal de Santa Maria da Feira", "Praia da Franquia (Vila Nova de Milfontes)", "Parque Florestal de Monsanto (Funchal)", "Jardim da Alagoa (Almada)",
"Centro de Interpretação de Arqueologia de Fundão", "Capela de São Frutuoso (Braga)", "Praia do Cabeço (Altura)", "Museu da Cortiça (Silves)", "Parque Urbano da Quinta da Conceição (Matosinhos)",
"Forte de São Tiago (Madeira)", "Praia do Forte Novo (Quarteira)", "Igreja do Salvador (Elvas)", "Aldeia da Cerdeira (Serra da Lousã)", "Ermida de Nossa Senhora da Paz (São Miguel)",
"Parque do Tejo e Trancão", "Praia do Areão (Vagos)", "Cais Palafítico da Carrasqueira", "Estação de Granja do Ulmeiro", "Praia Fluvial de Vimieiro (Penacova)",
"Forte de Santa Catarina (Figueira da Foz)", "Capela de Nossa Senhora da Saúde (Sousel)", "Museu da Indústria Têxtil (Covilhã)", "Miradouro do Monte do Facho (Póvoa de Varzim)", "Parque de Lazer de Albergaria-a-Velha",
"Praia de Vale Figueira (Aljezur)", "Ermida de Santa Luzia (Viana do Castelo)", "Museu do Azeite (Belmonte)", "Jardim do Largo de Camões (Ponte de Lima)", "Parque Urbano de Rio de Mouro",
"Praia do Abano (Cascais)", "Estação de Pereirinhas", "Forte de São Pedro de Alcântara", "Museu de Etnologia (Lisboa)", "Casa do Vinho Verde (Arcos de Valdevez)",
"Miradouro do Pico dos Barcelos (Madeira)", "Capela de São Brás (Elvas)", "Praia da Samoqueira (Porto Covo)", "Estação de Albufeira-Ferreiras", "Ermida da Nossa Senhora dos Remédios (Lamego)",
"Biblioteca Joanina (Coimbra)", "Praia do Medo da Fonte Santa (Portimão)", "Parque de Merendas da Albufeira do Caia", "Forte de São Lourenço (Almada)", "Capela de Nossa Senhora do Monte (Lisboa)",
"Jardim Botânico do Terceiro Milénio (Braga)", "Praia de Alburrica (Barreiro)", "Museu da Carris (Lisboa)", "Estação de Amendoeira", "Praia do Molhe (Porto)",
"Capela de Nossa Senhora dos Milagres (Açores)", "Praia da Lomba das Figueiras", "Estação de Pombal", "Museu Rural e do Vinho do Cartaxo", "Miradouro do Cabeço Gordo (Faial)",
"Praia de Vilarinho das Furnas", "Parque de Lazer da Mata da Misericórdia (Seia)", "Miradouro do Castelo de Marialva", "Casa do Artesanato (Montalegre)", "Parque da Várzea (Torres Vedras)",
"Praia do Pego (Comporta)", "Museu da Água (Lisboa)", "Capela do Senhor dos Milagres (Macieira de Cambra)", "Reserva Natural da Ponta de São Lourenço (Madeira)", "Praia de Buarcos",
"Jardim da Praça da República (Viana do Castelo)", "Miradouro do Castelo de Longroiva", "Museu do Cinema (Funchal)", "Capela de Nossa Senhora da Orada (Albufeira)", "Parque Urbano do Cercal do Alentejo",
"Jardim da Praça do Império (Lisboa)", "Praia do Burgau (Vila do Bispo)", "Museu do Brinquedo (Seia)", "Parque Linear da Ribeira das Naus (Lisboa)", "Igreja de Nossa Senhora da Graça (Estremoz)",
"Forte de Nossa Senhora da Graça (Elvas)", "Museu de Olaria (Barcelos)", "Praia da Franquia (Zambujeira do Mar)", "Parque de Merendas de Samora Correia", "Reserva Natural de Paul de Tornada (Caldas da Rainha)",
"Ermida de São Romão (Penha Garcia)", "Praia Fluvial de Cardigos", "Igreja de Santa Maria do Olival (Tomar)", "Estação de Alhandra", "Museu de Escultura Contemporânea (Montemor-o-Novo)",
"Miradouro do Alto da Lua (Serra de Monchique)", "Forte de São Tiago da Barra (Viana do Castelo)", "Museu das Comunidades (Albergaria-a-Velha)", "Praia de Vale dos Homens (Aljezur)", "Praia da Comenda (Setúbal)",
"Capela de São Marcos (Viseu)", "Forte de Nossa Senhora das Neves (Figueira da Foz)", "Centro Interpretativo do Vinho Verde (Melgaço)", "Miradouro do Monte da Penha (Guimarães)", "Parque Florestal de São Brás (Açores)",
"Praia de Vale Furado (Alcobaça)", "Museu da Água de Coimbra", "Ermida de Santa Catarina (Portimão)", "Parque do Fontelo (Viseu)", "Museu do Cristal de Alcobaça",
"Estação de Águas Santas", "Praia de Santa Eulália (Albufeira)", "Jardim Botânico José do Canto (Açores)", "Capela de Nossa Senhora da Alegria (Serra da Estrela)", "Praia Fluvial do Mosteiro (Pedrógão Grande)",
"Praia do Porto das Barcas", "Capela de Nossa Senhora da Piedade (Leiria)", "Estação de Freixo", "Museu da Electricidade (Lisboa)", "Ermida da Senhora da Lapa (Arouca)","Madeira","Açores","Monção", "Melgaço", "Vila Verde", "Celorico de Basto", "Fafe", "Cabeceiras de Basto",
"Mondim de Basto","Resende", "Ponte da Barca", "Paredes de Coura", "Caminha", "Valpaços", "Montalegre", "Boticas", "Vieira do Minho", "Terras de Bouro", "Esposende", "Santa Marta de Penaguião", "Ribeira de Pena", "Mira", "Tábua", "Arganil", "Mortágua", "Oliveira do Hospital", "Sever do Vouga", 
"Carregal do Sal", "Penacova", "Vila Nova de Poiares", "Vouzela", "Mangualde", "Nelas", "Tondela", "Castro Daire", "São Pedro do Sul", "Armamar", "Moimenta da Beira", "Penedono", "Aguiar da Beira", "Mêda", "Trancoso", "Arruda dos Vinhos", "Sobral de Monte Agraço", "Mafra", "Alenquer", "Lourinhã", "Cadaval", "Torres Vedras", "Azambuja", "Campo Maior", "Arronches", 
"Nisa", "Alter do Chão", "Crato", "Avis", "Fronteira", "Sousel", "Castro Verde", "Aljustrel", "Odemira", "Almodôvar", "Mértola", "Barrancos", "Vila Viçosa", "Borba", "Estremoz", "Arraiolos", "Vendas Novas", "Montemor-o-Novo", "Redondo", 
"Aljezur", "Vila do Bispo", "Loulé", "São Brás de Alportel", "Castro Marim", "Angra do Heroísmo", "Horta", "Vila do Porto", "Povoação", "Nordeste", "Ribeira Grande", "Vila Franca do Campo", "Lajes do Pico", "Santa Cruz das Flores", "Santa Cruz da Graciosa", "São Roque do Pico", "Madalena", "Velas", "Santana", "São Vicente", "Machico", "Câmara de Lobos",
"Ponta do Sol", "Calheta", "Porto Moniz", "Ribeira Brava", "Santa Cruz", "Monsaraz", "Castelo Rodrigo", "Marialva", "Sortelha", "Linhares da Beira", "Belmonte", "Almeida", "Piódão", "Talasnal", "Cerdeira", "Aldeia da Pena", "Drave", "Foz d'Égua", 
"Dornes", "Corvo", "Vila Baleira", "Porto Judeu", "Lajes das Flores", "Praia Formosa"}
